general dashboard cleanup last step
calblueprint/ks-web pull request #13
Opened 2020-10-31 21:43 UTC by halimousine

[//]: # "These comments meant for your reference, they are invisible and don't need to be deleted"

## What's new in this PR?

Removed files for general dashboard announcements. Expanded white box for general dashboard and changed css. got rid of people power card component with photo. 

### How to Review

[//]: # 'The order in which to review files and 
what to expect when testing locally'
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'

### Related PRs

[//]: # "Optional - related PRs you're waiting on
/ PRs that will conflict, etc"
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'

### Next steps

[//]: # "What doesn't work yet, what's NOT in this 
PR/has to be done "
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'

### Screenshots

Before: 
![image](https://user-images.githubusercontent.com/43193441/97790638-7ebd8900-1ba0-11eb-960d-444fb1da6081.png)

AFTER: 
![image](https://user-images.githubusercontent.com/43193441/97790641-84b36a00-1ba0-11eb-8ab2-a7d2790d0a9b.png)

### Design Status

[//]: # 'If this is a frontend PR, what is the expected 
status of the UI in this PR (lo, mid, high- fi?'
[//]: # '####### LOFI/MIDFI/HIFI ###########'
[//]: # '############## END ##################'

CC: @dfangshuo

2020-10-31 21:46 UTC, phoebeli23 approved these changes

2020-11-02 03:13 UTC, aliceyezhao approved these changes

2020-11-02 03:29 UTC, niwong requested changes
Go ahead and make those changes that I commented and feel free to merge in when finished! Nice job, Andy.

2020-11-02 03:29 UTC, niwong commented on src/styles/GeneralOwnerDashboard.css
> +  margin-right: 10rem;
--

2020-11-02 03:29 UTC, niwong commented on src/styles/GeneralOwnerDashboard.css
>    margin-top: 55px;
Replace all margin tags from this class and replace with `margin: 60px`

2020-11-02 03:29 UTC, niwong commented on src/styles/GeneralOwnerDashboard.css
>    margin-top: 55px;
Also remove `width` from `.dashboard`. This should make the white box a bit nicer.

2020-11-02 03:29 UTC, niwong commented on src/styles/GeneralOwnerDashboard.css
> +  margin-right: 10rem;
Remove `margin-right: 10rem`

2020-11-08 00:48 UTC, niwong approved these changes
Looks great!

2020-11-08 00:52 UTC, merged