Phoebe/farm profile page
calblueprint/ks-web pull request #22
Opened 2020-11-22 07:49 UTC by phoebeli23

[//]: # "These comments meant for your reference, they are invisible and don't need to be deleted"

## What's new in this PR?

Created Farm Profile Page (for farms participating in Food Hub)
Accessible at route localhost:3000/farm/:id
https://www.notion.so/77891b5a221c435ba97bdff45d6adb39?v=eba74d9aeb7b447a898462fe7b5222c2&p=5692bdbb85644e8c9596c8710fb94947

### How to Review

New Files:
1. FarmProfile.js
2. FarmContactCard.js
3. FarmProfile.css

FarmProfile.js is the farm profile page component, which renders FarmContactCard.js
Both files use FarmProfile.css for styling 

### Related PRs

[//]: # "Optional - related PRs you're waiting on
/ PRs that will conflict, etc"
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'

### Next steps

Pipe in real data
Optimize CSS: align text and icons, make responsive

### Screenshots

![farmProfilePageScreenshot](https://user-images.githubusercontent.com/55935661/99897981-c50f8080-2c52-11eb-8b1f-3ee9c49d1930.png)

### Design Status

[//]: # 'If this is a frontend PR, what is the expected 
status of the UI in this PR (lo, mid, high- fi?'
[//]: # '####### LOFI/MIDFI/HIFI ###########'
[//]: # '############## END ##################'

yay css is hard

CC: @dfangshuo

2020-11-23 04:16 UTC, aliceyezhao requested changes
Just some convention stuff which has to do with other stuff that we need to discuss as a team as well. Great job with this! 

Also, remove your yarn.lock file from git since it is autogenerated locally

2020-11-23 04:16 UTC, aliceyezhao commented on src/styles/FarmProfile.css
> +  color: rgba(51, 51, 51, 0.5);
We should make a file of color hex codes and import them for consistency.

2020-11-23 04:16 UTC, aliceyezhao commented on src/styles/FarmProfile.css
> +  font-family: 'Inter', sans-serif;
We should also change fonts globally in App.css to save some lines. I kept the default fonts for now

2020-11-23 04:16 UTC, aliceyezhao commented on src/screens/farmProfile/components/FarmContactCard.js
> +    // const { id, farmName, farmerName, phone, email, address, location, inspector } = this.props;
delete

2020-11-23 04:16 UTC, aliceyezhao commented on src/screens/farmProfile/FarmProfile.js
> +    const { id } = match.params;
rename to `farmId`

2020-11-23 04:16 UTC, aliceyezhao commented on src/screens/farmProfile/FarmProfile.js
> +    const { match } = this.props;
This is extracting the farmID from the route URL right? Maybe rename it unless if this is convention.

2020-11-23 04:16 UTC, aliceyezhao commented on src/screens/farmProfile/FarmProfile.js
> +              gapCertified
should you set this?

2020-11-30 03:51 UTC, halimousine approved these changes
looks goooood!
- bottom card leaks out of the largest container so that should be fixed on the next PR. 
- good job with all the props I forgot to do that with my pr wops

2020-11-30 03:55 UTC, aliceyezhao commented on src/screens/farmProfile/components/FarmContactCard.js
> +                  </div>
@halimousine this is an example of conditional rendering

2020-11-30 03:55 UTC, aliceyezhao approved these changes

2020-11-30 04:12 UTC, merged

2020-12-03 00:55 UTC, niwong reviewed
Late to the party but this is some beautiful code. Nice job @phoebeli23 and thank you so much @aliceyezhao for reviewing and leaving insightful comments. Looking great, team.