Divi/sign up
calblueprint/ks-web pull request #56
Opened 2021-04-05 04:17 UTC by didvi

[//]: # "These comments meant for your reference, they are invisible and don't need to be deleted"

## What's new in this PR?
Sign up page

### How to Review
`SignUp.js` is the main part
removed some junk in `utils.js`
made some changes to Myles' input and dropdown components (mostly just adding props)--will need to make sure they still work for his page and merge after his is merged

[//]: # 'The order in which to review files and 
what to expect when testing locally'
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'

### Related PRs
Myles' PRs
[//]: # "Optional - related PRs you're waiting on
/ PRs that will conflict, etc"
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'

### Design Status

[//]: # 'If this is a frontend PR, what is the expected 
status of the UI in this PR (lo, mid, high- fi?'
[//]: # '####### LOFI/MIDFI/HIFI ###########'
[//]: # '############## END ##################'

CC: @phoebeli23 @mylesdomingo

2021-04-08 19:58 UTC, phoebeli23 requested changes
- Clicking "Submit" to sign up does not work for me; generates the following error
<img width="301" alt="Screen Shot 2021-04-08 at 12 57 07 PM" src="https://user-images.githubusercontent.com/55935661/114088506-ef608400-9869-11eb-84f5-a46affdfa342.png">

- Styling/prop error 
<img width="307" alt="Screen Shot 2021-04-08 at 12 55 28 PM" src="https://user-images.githubusercontent.com/55935661/114088266-b2948d00-9869-11eb-9120-63ff4f806d19.png">

2021-04-09 00:51 UTC, mylesdomingo requested changes

2021-04-09 00:51 UTC, mylesdomingo commented on src/screens/shared/auth/SignUp.js
> +    this.handleChange = this.handleChange.bind(this);
You can use arrow functions in a react class component to bind to `this` without calling bind. (eg. `handleChange = (name) => { ... }`)

2021-04-09 00:51 UTC, mylesdomingo commented on src/screens/shared/auth/SignUp.js
> +              'background-color': 'var(--ks-dark-blue)',
change to `backgroundColor` 

use camelCase for MUI components

2021-04-09 00:51 UTC, mylesdomingo commented on src/screens/shared/auth/SignUp.js
> +      userTypes: '',
`userTypesIndex` should be initialized at 1 or 0 or '', 
![image](https://user-images.githubusercontent.com/35586281/114112976-6f9adf80-9892-11eb-9d31-0b5c06fe1ee8.png)

2021-04-09 00:51 UTC, mylesdomingo commented on src/screens/shared/auth/SignUp.js
> +                value={firstName}
we need to short circuit the values to fix the uncontrolled warning in the console. can you add this into the `FieldInput` code? 

example: `value={this.state.input || ""}`

2021-04-09 00:51 UTC, mylesdomingo commented on src/screens/shared/auth/SignUp.js
> +        newErrors[field] = errorMessage;
![image](https://user-images.githubusercontent.com/35586281/114113249-0a93b980-9893-11eb-83b8-2676cf36bd14.png)

getting this error when i submit

2021-04-09 00:54 UTC, mylesdomingo commented on src/screens/shared/auth/SignUp.js
> +                value={firstName}
https://stackoverflow.com/questions/47012169/a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-erro

2021-04-09 01:07 UTC, didvi commented
Resolved warnings in the console. User creation should work if you have this on your backend https://github.com/calblueprint/bp-boilerplate-backend/pull/9

2021-04-12 04:22 UTC, phoebeli23 commented
Things to address:
- See the screenshot from my earlier comment ("Unsupported style property background-color")
- Please center the component and move the submit button to the right ([refer to figma](https://www.figma.com/file/vWdNmoKEuSF24x9OYN9vJh/KS-NSEVP-Wireframes?node-id=2858%3A43041))

2021-04-17 22:40 UTC, merged