Sandra/data dashboard
calblueprint/ks-web pull request #65
Opened 2021-04-16 00:15 UTC by sandrazavala

[//]: # "These comments meant for your reference, they are invisible and don't need to be deleted"

## What's new in this PR?

[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'
Live data is in KS and NSEVP dashboard
### How to Review

[//]: # 'The order in which to review files and 
what to expect when testing locally'
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'
Changes made in StatCards.js, Dashboard.js, App,js, SuspenseRoute.js.
Created DashUtils.js to call from airtable and deleted NSEVPDashboard.js and KSDashboard.js
### Related PRs

[//]: # "Optional - related PRs you're waiting on
/ PRs that will conflict, etc"
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'
currently have a merge conflict with current master. Cannot pull from master as it conflicts with changes in StatCard.js, Dashboard.js.

### Next steps

[//]: # "What doesn't work yet, what's NOT in this 
PR/has to be done "
[//]: # '####### YOUR ANSWER BELOW ###########'
[//]: # '############## END ##################'
Merge conflict needs to be resolved. This is the current error:
"src/screens/ks/dashboard/KSDashboard.js: needs merge
src/screens/nsevp/dashboard/NSEVPDashboard.js: needs merge
src/screens/shared/dashboard/Dashboard.js: needs merge
error: you need to resolve your current index first"
### Screenshots

[//]: # '#### YOUR SCREENSHOTS BELOW ########'
[//]: # '############## END ##################'

### Design Status

[//]: # 'If this is a frontend PR, what is the expected 
status of the UI in this PR (lo, mid, high- fi?'
[//]: # '####### LOFI/MIDFI/HIFI ###########'
[//]: # '############## END ##################'

CC: @phoebeli23

2021-04-18 01:28 UTC, phoebeli23 submitted a review, later dismissed
Great work Sandra! I left some comments. Also, for consistency please capitalize variable names that contain "KS", "NSEVP", or "GAP" (so `percentKsGapApplied` would become `percentKSGAPApplied`

2021-04-18 01:28 UTC, phoebeli23 commented on src/lib/dashUtils.js
> +  const singleGapCertfication = await getTotalHarvestById(id);
typo !

2021-04-18 01:28 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    const numGapCertified = gapCertification.filter(farm => farm.gapCertified); // in gap certification there is no ks affiliated column
@mylesdomingo What is the best way to get all KS-affiliated farms that are GAP certified?
The KS-affiliated field is in the Farms table, but the GAP Certified field is in its own table.

2021-04-18 01:28 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    }
Round to the nearest integer please

2021-04-18 01:28 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    ).length;
Same issue as above, we need to access the number of KS-affiliated farms that are GAP accepted.

2021-04-18 01:28 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    const totalHarvestsPounds = total;
Could you declare `let totalHarvestsPounds` so you don't need the `total` variable?

2021-04-18 01:28 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    const nsevpHarvestFarms = recentHarvests.length;
Will have to update the logic for getting the number of harvesting farms
@niwong

2021-04-18 01:28 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    );
Same as above

2021-04-24 19:09 UTC, phoebeli23 requested changes

2021-04-24 19:09 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    }
can this be done using map and filter funtions?

2021-04-24 19:09 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    const numGAPCertified = GAPCertification.filter(farm => farm.gapCertified);
this has to be updated with the schema change for gapCertified

2021-04-24 19:09 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +    ).length;
also need to add condition that the farm is a KS-affiliated farm

2021-04-24 19:09 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +
same as above

2021-04-24 19:09 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +          description: 'are harvesting this week'
We made an update to this stat card! You will need to filter for farms in recent harvests with dates in the past 7 days, then remove all duplicate farms (so we are only left with a list of unique farms)

Ask @mylesdomingo about date filtering

![Screen Shot 2021-04-24 at 12 07 52 PM](https://user-images.githubusercontent.com/55935661/115970183-b4ab4c80-a4f5-11eb-9d57-347044340274.png)

2021-04-24 19:46 UTC, merged

2021-04-26 23:33 UTC, sandrazavala commented on src/screens/shared/dashboard/StatCards.js
> +
KSGAP represents the farms that are KS-affiliated!

2021-04-27 03:42 UTC, phoebeli23 commented on src/screens/shared/dashboard/StatCards.js
> +
Oops you're right!